printers:
  MK4:
    name: "Original Prusa MK4S HF0.4 nozzle - aline"
    filaments: ["Generic PETG - aline"]
    profiles: ["0.20mm SPEED - aline"]
    apply_filament_settings: True

fill_pattern:
  rectilinear: "Rectiligne"
  honeycomb: "Nid d'abeille"
  gyroid: "Gyroide"
  adaptivecubic: "Cubique Adaptatif"

fill_density: ["5%", "10%", "20%", "40%", "60%"]

prusa_path: "C:/Program Files/Prusa3D/PrusaSlicer/prusa-slicer.exe"
config_path: "./config"
prusa_config_path: "C:/Users/aline/AppData/Roaming/PrusaSlicer"