printers:
  MK4:
    name: "Original Prusa MK4S HF0.4 nozzle - aline"
    physical_printers: []
    nozzles:
      0.4mm:
        filaments: ["Prusament PETG @MK4S HF0.4 - aline", "Prusament PLA @MK4S HF0.4 - aline"]
        profiles: ["0.20mm SPEED @MK4S HF0.4 - aline"]
    extruders: ["0.4mm"]

  XL:
    name: "Original Prusa XL - 5T Input Shaper 0.4 et 0.6 nozzle - aline"
    physical_printers: []
    nozzles:
      0.4mm:
        filaments: ["Prusament PETG @XL 0.4 - aline", "Prusament PLA @XL 0.4 - aline"]
        profiles: ["0.20mm SPEED @XL 0.4 - aline"]
      0.6mm:
        filaments: ["Prusament PETG @XL 0.6 - aline", "Prusament PLA @XL 0.6 - aline"]
        profiles: ["0.20mm SPEED @XL 0.6 - aline"]
    extruders: ["0.4mm", "0.4mm", "0.4mm", "0.4mm", "0.6mm"]

fill_pattern:
  rectilinear: "Rectiligne"
  honeycomb: "Nid d'abeille"
  gyroid: "Gyroide"
  adaptivecubic: "Cubique Adaptatif"

fill_density: ["5%", "10%", "20%", "40%", "60%"]

prusa_path: "C:/Program Files/Prusa3D/PrusaSlicer/prusa-slicer.exe"
prusa_datadir: "C:/Users/aline/AppData/Roaming/PrusaSlicer"